name: Semantic Pull Request

on:
    pull_request_target:
        types:
            - edited
            - opened
            - synchronize

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    validate-title:
        name: Validate Title
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Validate pull request title
              uses: amannn/action-semantic-pull-request@01d5fd8a8ebb9aafe902c40c53f0f4744f7381eb
